import { allQuestions, modulesWithQuestions } from '../data/questions'
import { type ProgressState, dueQuestionIds, moduleCompletion, moduleScore } from '../lib/progress'
import { REVIEW_SESSION_SIZE } from '../lib/selection'

export function ReviewView({ progress, onStart, onOpenModule }: { progress: ProgressState; onStart: () => void; onOpenModule: (id: string) => void }) {
  const due = dueQuestionIds(progress, allQuestions)
  const weakModules = modulesWithQuestions.map((module) => ({ module, score: moduleScore(progress, module.questionIds), completion: moduleCompletion(progress, module.questionIds) })).filter(({ completion }) => completion > 0).sort((a, b) => a.score - b.score).slice(0, 4)
  return <div className="page-stack review-page"><section className="section-heading"><div><p className="eyebrow">MEMORIA ACTIVA</p><h1>Repaso adaptativo</h1><p>La cola reúne las preguntas que has fallado o respondido con confianza 1 o 2. Cada repaso toma las {REVIEW_SESSION_SIZE} primeras: primero los fallos con confianza 4 o 5, después el resto de fallos y por último los aciertos con confianza 1 o 2; dentro de cada grupo, los más antiguos primero.</p></div><button className="button-primary" onClick={onStart} disabled={!due.length}>Empezar repaso <span>{Math.min(REVIEW_SESSION_SIZE, due.length)} →</span></button></section><div className="review-banner"><div className="review-banner-number" data-testid="review-count">{due.length}</div><div><strong>{due.length === 1 ? 'pregunta pendiente de repaso' : 'preguntas pendientes de repaso'}</strong><p>{due.length ? 'Una pregunta sale de la cola cuando la aciertas dos veces seguidas con confianza 3 o más.' : 'No tienes preguntas pendientes. Cuando falles una o la respondas con confianza 1 o 2, aparecerá aquí.'}</p></div></div><section className="review-grid"><div className="content-panel"><div className="panel-heading"><div><p className="eyebrow">DOMINIOS A REFORZAR</p><h2>Tu mapa de precisión</h2></div></div>{weakModules.length ? weakModules.map(({ module, score, completion }) => <button className="weak-module" key={module.id} onClick={() => onOpenModule(module.id)}><span className="weak-module-number">{String(module.order).padStart(2, '0')}</span><span><strong>{module.title}</strong><small>{completion}% completado · score {score}%</small></span><span className="weak-module-arrow">→</span></button>) : <p className="empty-state">Todavía no hay suficientes intentos para calcular dominios débiles. Empieza por el mapa.</p>}</div><div className="content-panel review-principles"><p className="eyebrow">CÓMO FUNCIONA</p><h2>Menos repetición, más precisión.</h2><ol><li><b>1</b><span>Entra en la cola lo fallado o respondido con confianza 1 o 2.</span></li><li><b>2</b><span>La explicación vuelve a la documentación oficial.</span></li><li><b>3</b><span>Sale tras dos aciertos seguidos con confianza 3 o más.</span></li></ol></div></section></div>
}
