import { useEffect, useRef, useState } from 'react'
import type { QuestionBucket } from '../data/types'
import type { Session } from '../app/types'
import { GuideLink } from '../components/GuideLink'
import { InlineText } from '../components/InlineText'
import { bucketLabels } from '../app/labels'
import { modulesWithQuestions } from '../data/question-catalog'
import { loadedQuestion } from '../data/question-loader'
import { scoreAttempt } from '../lib/progress'
import { type GuideRef, groupBySection, guideRefFor } from '../lib/guide-links'

export function SessionResult({ session, answers, flagged, onHome, onReview, onRetry, onOpenGuide, onModule }: { session: Session; answers: Record<string, string[]>; flagged: string[]; onHome: () => void; onReview: () => void; onRetry: (ids: string[]) => void; onOpenGuide: (ref: GuideRef) => void; onModule: () => void }) {
  // La sesión solo arranca con sus preguntas descargadas, así que aquí están todas.
  const questions = session.questionIds.flatMap((id) => loadedQuestion(id) ?? [])
  const results = questions.map((question) => scoreAttempt(question, answers[question.id] ?? []))
  const score = Math.round(results.reduce((sum, result) => sum + result.score, 0) / results.length * 100)
  const correct = results.filter((result) => result.correct).length
  const mock = session.mode === 'mock'
  const unanswered = questions.filter((question) => !(answers[question.id] ?? []).length).length
  const bucketResults = (Object.keys(bucketLabels) as QuestionBucket[]).map((bucket) => { const indexes = questions.map((question, index) => ({ question, index })).filter(({ question }) => question.bucket === bucket).map(({ index }) => index); const value = indexes.length ? Math.round(indexes.reduce((sum, index) => sum + results[index].score, 0) / indexes.length * 100) : 0; return { bucket, value, count: indexes.length } }).filter(({ count }) => count > 0)
  const moduleResults = modulesWithQuestions.map((module) => { const indexes = questions.map((question, index) => ({ question, index })).filter(({ question }) => question.moduleId === module.id).map(({ index }) => index); return { module, total: indexes.length, correct: indexes.filter((index) => results[index].correct).length } }).filter(({ total }) => total > 0)
  const missedQuestions = questions.filter((_, index) => !results[index].correct)
  const missed = missedQuestions.map((question) => question.id)
  const sectionsToReview = groupBySection(missedQuestions)
  const [showAllSections, setShowAllSections] = useState(false)
  // Al entregar el simulacro (o terminar una sesión) el botón pulsado desaparece: el foco va al título del resultado.
  // La ruta no cambia al entregar, así que no compite con el foco del router.
  const titleRef = useRef<HTMLHeadingElement>(null)
  useEffect(() => { titleRef.current?.focus() }, [])
  const visibleSections = showAllSections ? sectionsToReview : sectionsToReview.slice(0, 8)
  const flaggedQuestions = flagged.filter((id) => session.questionIds.includes(id))
  const moduleLabel = (moduleId: string) => { const module = modulesWithQuestions.find((item) => item.id === moduleId); return module ? `${String(module.order).padStart(2, '0')} ${module.title}` : moduleId }
  return <div className="page-stack result-page">
    <section className="result-hero"><p className="eyebrow">{mock ? 'SIMULACRO COMPLETADO' : 'SESIÓN COMPLETADA'}</p><h1 ref={titleRef} tabIndex={-1} className="result-title">{session.title}</h1><div className="result-score"><strong>{score}%</strong><span>{correct} de {session.questionIds.length} respuestas exactas{unanswered ? ` · ${unanswered} sin responder` : ''}</span></div><p>{score >= 80 ? 'Buen nivel. Repasa los apartados de abajo para cerrar los huecos que quedan.' : 'Usa los errores como guía: cada fallo te lleva al apartado exacto de la guía donde está la respuesta.'}</p></section>
    {moduleResults.length > 1 && <section className="content-panel result-modules"><div className="panel-heading"><div><p className="eyebrow">RESULTADO POR BLOQUE</p><h2>Dónde has acertado y dónde no</h2></div><span className="panel-count">{moduleResults.length} bloques</span></div>{moduleResults.map(({ module, total, correct: ok }) => { const value = Math.round(ok / total * 100); return <div className={`result-row ${value < 70 ? 'weak' : ''}`} key={module.id}><span>{String(module.order).padStart(2, '0')} {module.title}</span><div className="thin-progress"><span style={{ width: `${value}%` }} /></div><strong>{ok}/{total}</strong></div> })}</section>}
    {sectionsToReview.length > 0 && <section className="content-panel result-sections"><div className="panel-heading"><div><p className="eyebrow">QUÉ ESTUDIAR AHORA</p><h2>Apartados de la guía con fallos</h2></div><span className="panel-count">{sectionsToReview.length} apartados</span></div><div className="section-miss-list">{visibleSections.map((group) => { const first = loadedQuestion(group.questionIds[0]); const ref = first && guideRefFor(first); return <button type="button" className="section-miss" key={`${group.moduleId}-${group.sectionId}`} onClick={() => ref && onOpenGuide(ref)}><span className="section-miss-count">{group.questionIds.length}</span><span><small>{moduleLabel(group.moduleId)}</small><strong><InlineText text={group.title} /></strong></span><b aria-hidden="true">→</b></button> })}</div>{sectionsToReview.length > visibleSections.length && <button type="button" className="button-quiet section-miss-more" onClick={() => setShowAllSections(true)}>Ver los {sectionsToReview.length} apartados ↓</button>}</section>}
    <section className="result-grid"><div className="result-breakdown"><div className="panel-heading"><div><p className="eyebrow">LECTURA DEL RESULTADO</p><h2>Precisión por tipo</h2></div></div>{bucketResults.map(({ bucket, value }) => <div className="result-row" key={bucket}><span>{bucketLabels[bucket]}</span><div className="thin-progress"><span style={{ width: `${value}%` }} /></div><strong>{value}%</strong></div>)}<p className="result-footnote">{flaggedQuestions.length ? `${flaggedQuestions.length} pregunta(s) marcada(s) para revisar.` : 'No has marcado preguntas en esta sesión.'}</p></div><div className="result-actions"><p className="eyebrow">SIGUIENTE PASO</p><h2>Convierte el error en memoria.</h2><p>{missed.length ? `Repite ahora las ${missed.length} que has fallado, en otro orden y con las opciones barajadas.` : 'Sin fallos en esta sesión. El repaso adaptativo prioriza lo menos practicado.'}</p>{missed.length > 0 && <button className="button-primary" onClick={() => onRetry(missed)}>Repetir los fallos <span>{missed.length} →</span></button>}<button className={missed.length ? 'button-outline' : 'button-primary'} onClick={onReview}>Repaso adaptativo <span>→</span></button><button className="button-outline" onClick={onModule}>{session.sectionId ? 'Volver al apartado' : 'Volver al módulo'}</button><button className="button-quiet" onClick={onHome}>Inicio</button></div></section>
    <section className="result-review"><div className="panel-heading"><div><p className="eyebrow">REVISIÓN DEL TEST</p><h2>{missed.length} respuestas para revisar</h2></div></div>{missedQuestions.map((question) => { const selected = answers[question.id] ?? []; const ref = guideRefFor(question); return <article className="result-review-item" key={question.id}><small>{moduleLabel(question.moduleId)} · {question.id}{flaggedQuestions.includes(question.id) ? ' · ⚑ marcada' : ''}</small><h3><InlineText text={question.promptEs} /></h3><p><b>Tu respuesta:</b> <InlineText text={selected.length ? question.options.filter((option) => selected.includes(option.id)).map((option) => option.text).join(' / ') : 'Sin respuesta'} /></p><p><b>Respuesta correcta:</b> <InlineText text={question.options.filter((option) => question.correctOptionIds.includes(option.id)).map((option) => option.text).join(' / ')} /></p><p><InlineText text={question.explanationEs} /></p>{ref && <GuideLink question={question} onOpenGuide={() => onOpenGuide(ref)} />}<div className="result-review-sources">{question.sourceRefs.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.title} ↗</a>)}</div></article> })}</section>
  </div>
}
